import { verify, createPublicKey } from "node:crypto";

// ─── Embedded Ed25519 public key (generated by scripts/generate-keypair.ts) ──

const PUBLIC_KEY_PEM = `-----BEGIN PUBLIC KEY-----
MCowBQYDK2VwAyEAGr/ILyXYlJ6IP2bAVP/mmqbONfd17m8gJcN/N1qI03g=
-----END PUBLIC KEY-----`;

const publicKey = createPublicKey(PUBLIC_KEY_PEM);

// ─── Types ───────────────────────────────────────────────

export interface LicensePayload {
  company: string;
  expiry: string; // YYYY-MM-DD
  issuedAt: string; // YYYY-MM-DD
}

export interface LicenseValidation {
  valid: boolean;
  payload?: LicensePayload;
  company?: string;
  expiry?: Date;
  error?: string;
}

export interface LicenseStatus {
  registered: boolean;
  valid: boolean;
  expired: boolean;
  degraded: boolean;
  gracePeriod: boolean;
  company: string | null;
  expiry: string | null;
  graceExpiresAt: string | null;
}

// ─── Grace period ────────────────────────────────────────

const GRACE_PERIOD_DAYS = 30;

// ─── Validate a license key string ───────────────────────

export function validateLicense(licenseKey: string): LicenseValidation {
  if (!licenseKey || !licenseKey.includes(".")) {
    return { valid: false, error: "Invalid license key format" };
  }

  const dotIndex = licenseKey.lastIndexOf(".");
  const payloadB64 = licenseKey.slice(0, dotIndex);
  const signatureB64 = licenseKey.slice(dotIndex + 1);

  if (!payloadB64 || !signatureB64) {
    return { valid: false, error: "Invalid license key format" };
  }

  // Verify signature
  try {
    const signature = Buffer.from(signatureB64, "base64");
    const isValid = verify(null, Buffer.from(payloadB64), publicKey, signature);
    if (!isValid) {
      return { valid: false, error: "Invalid license key signature" };
    }
  } catch {
    return { valid: false, error: "Invalid license key signature" };
  }

  // Decode payload
  let payload: LicensePayload;
  try {
    const json = Buffer.from(payloadB64, "base64").toString("utf-8");
    payload = JSON.parse(json);
  } catch {
    return { valid: false, error: "Corrupted license payload" };
  }

  if (!payload.company || !payload.expiry) {
    return { valid: false, error: "Incomplete license payload" };
  }

  const expiry = new Date(payload.expiry + "T23:59:59.999Z");
  if (isNaN(expiry.getTime())) {
    return { valid: false, error: "Invalid expiry date in license" };
  }

  return {
    valid: true,
    payload,
    company: payload.company,
    expiry,
  };
}

// ─── Get full license status from DB ─────────────────────

interface PrismaLike {
  setting: {
    findUnique(args: {
      where: { key: string };
    }): Promise<{ value: string } | null>;
  };
}

export async function getLicenseStatus(
  prisma: PrismaLike,
): Promise<LicenseStatus> {
  const [keyRow, installDateRow] = await Promise.all([
    prisma.setting.findUnique({ where: { key: "reg.licenseKey" } }),
    prisma.setting.findUnique({ where: { key: "system.installDate" } }),
  ]);

  const licenseKey = keyRow?.value ?? "";
  const installDateStr = installDateRow?.value ?? "";

  // Calculate grace period
  const installDate = installDateStr ? new Date(installDateStr) : new Date();
  const graceExpiresAt = new Date(installDate);
  graceExpiresAt.setDate(graceExpiresAt.getDate() + GRACE_PERIOD_DAYS);
  const now = new Date();
  const graceActive = now < graceExpiresAt;

  // No license key at all
  if (!licenseKey) {
    return {
      registered: false,
      valid: false,
      expired: false,
      degraded: !graceActive,
      gracePeriod: graceActive,
      company: null,
      expiry: null,
      graceExpiresAt: graceExpiresAt.toISOString(),
    };
  }

  // Validate the key
  const result = validateLicense(licenseKey);

  if (!result.valid) {
    return {
      registered: true,
      valid: false,
      expired: false,
      degraded: true,
      gracePeriod: false,
      company: null,
      expiry: null,
      graceExpiresAt: null,
    };
  }

  const expired = result.expiry! < now;

  return {
    registered: true,
    valid: true,
    expired,
    degraded: expired,
    gracePeriod: false,
    company: result.company ?? null,
    expiry: result.payload?.expiry ?? null,
    graceExpiresAt: null,
  };
}
